
.PHONY:ft, lm, b,kg,c,f,c, far
ft:
	go run main.go 0ft
lm:
	go run main.go 1m
b:
	go run main.go 1.23lb
kg:
	go run main.go -4.56kg
c:
	go run main.go 1e3c
f:
	go run main.go -1e-2f
cel:
	go run main.go 32°C
far:
	go run main.go 212°F